name: Main

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: "latest"

      - name: Install Dependencies
        run: pnpm install

      - name: Check Lint
        run: pnpm lint

      - name: Check Format
        run: pnpm format

      - name: Build
        run: pnpm build
